version: "3"

services:

  app:
    build: .
    container_name: service_demo
    depends_on:
      - postgres
      - redis
    ports:
      - "80:8080"

  spiders:
    build: web_spiders
    container_name: spiders_demo
    depends_on:
      - postgres
    environment:
      - SPIDERS_EVN=production
      - RUN_WITH_SCHEDULER=True
      - SPIDER_NAME=login_quotes

  redis:
    container_name: redis_demo
    image: redis:alpine
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis-data:/var/lib/redis/data

  postgres:
    container_name: postgres_demo
    image: postgres:alpine
    restart: always
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_dbdata:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres_dbdata: